apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: frontend-graphtuitous
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frontend-graphtuitous
    app.kubernetes.io/part-of: graphtuitous
  name: frontend-graphtuitous
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: frontend-graphtuitous
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: frontend-graphtuitous
    spec:
      containers:
      - image: quay.io/jduimovich0/frontend
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
