apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: frontend-graphtuitous
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frontend-graphtuitous
    app.kubernetes.io/part-of: graphtuitous
  name: frontend-graphtuitous
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: frontend-graphtuitous
status:
  loadBalancer: {}
